# Generated by Django 3.2.5 on 2021-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cls', models.IntegerField(default=None)),
                ('section', models.CharField(max_length=200)),
                ('roll_no', models.IntegerField(default=None, null=True)),
                ('physical_fitness', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=2)),
                ('mental_fitness', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=2)),
            ],
        ),
    ]
